@startuml Biểu đồ Use Case

skinparam linetype polylin
left to right direction


:Nhân viên thu ngân: as cashier
:Quản lý: as manager
:Khách hàng vãng lai: as guest
:Khách hàng thành viên: as member

guest <|-- member

usecase "Đăng nhập hệ thống" as UC_QT0


package "Bán hàng" { 
    usecase "Tạo đơn hàng nhanh" as UC_BH1
    usecase "Thanh toán" as UC_BH2
    usecase "Đóng ca làm việc" as UC_BH3
    usecase "In thông tin đơn hàng" as UC_BH4
}

package "Quản trị" {
    usecase "Quản lý Thực đơn & Giá" as UC_QT1
    usecase "Quản lý Nhân viên" as UC_QT2
    usecase "Báo cáo & Dự báo" as UC_QT3
}

package "Khách hàng" {
    usecase "Xem thực đơn hôm nay" as UC_KH1
    usecase "Đặt hàng trực tuyến" as UC_KH2
    usecase "Đăng nhập" as UC_KH3
    usecase "Đăng ký" as UC_KH4
    usecase "Xem lịch sử mua hàng" as UC_KH5
    usecase "Gửi feedback" as UC_KH6
    usecase "Xem giỏ hàng" as UC_KH7
}

cashier --> UC_QT0
manager --> UC_QT0


UC_BH1 ..> UC_QT0 : <<include>>
UC_QT1 ..> UC_QT0 : <<include>>
UC_QT2 ..> UC_QT0 : <<include>>
UC_QT3 ..> UC_QT0 : <<include>>

cashier --> UC_BH1
cashier --> UC_BH3
UC_BH2 .> UC_BH1 : <<include>>
UC_BH4 .> UC_BH1 : <<include>>
' UC3 .> UC2 : <<extend>>


manager --> UC_QT1
manager --> UC_QT2
manager --> UC_QT3

guest --> UC_KH1
guest --> UC_KH3
guest --> UC_KH4

member --> UC_KH2
member --> UC_KH5
member --> UC_KH6
member --> UC_KH7

@enduml