#!/bin/bash

# Script to set Gmail App Password for password reset functionality
# Run: ./setup_mail.sh

echo "=== Cấu hình Gmail SMTP cho Cơm Bình Dân ==="
echo ""
echo "Hướng dẫn lấy App Password từ Google:"
echo "1. Truy cập: https://myaccount.google.com/apppasswords"
echo "2. Đăng nhập tài khoản Gmail (cần bật 2-Step Verification)"
echo "3. Chọn App: 'Mail' và Device: 'Other (Custom name)'"
echo "4. Đặt tên: 'Cơm Bình Dân' và nhấn 'Generate'"
echo "5. Copy mã 16 ký tự (ví dụ: abcd efgh ijkl mnop)"
echo ""

read -p "Nhập Gmail App Password (16 ký tự, không có dấu cách): " APP_PASSWORD

# Remove any spaces
APP_PASSWORD=$(echo "$APP_PASSWORD" | tr -d ' ')

if [ ${#APP_PASSWORD} -ne 16 ]; then
    echo "⚠️  Cảnh báo: App Password thường có 16 ký tự. Đã nhập ${#APP_PASSWORD} ký tự."
fi

# Update .env file
cat > .env << EOF
# Gmail SMTP Configuration
# Generated by setup_mail.sh

MAIL_USERNAME=leducluong0413@gmail.com
MAIL_PASSWORD=$APP_PASSWORD
EOF

echo ""
echo "✅ Đã lưu cấu hình vào file .env"
echo ""
echo "Để áp dụng, chạy lệnh:"
echo "  docker compose down && docker compose up -d --build"
echo ""
