@startuml Biểu đồ use case phân rã Quản lý nhân viên



:Quản lý: as manager
left to right direction

usecase "Xem danh sách nhân viên" as uc1
usecase "Thêm nhân viên" as uc2
usecase "Xóa nhân viên" as uc3
usecase "Sửa thông tin nhân viên" as uc4

manager --> uc1
manager --> uc2
manager --> uc3
manager --> uc4

@enduml